package lab2;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JOptionPane;

/**
 *
 * @author jmiller
 */
public class SimpleDateTimeWindow extends javax.swing.JFrame {

    private Calendar endDateTime = Calendar.getInstance();
    private Calendar startDateTime = Calendar.getInstance();
    private final String TIME_DATE_FORMAT = "MM-dd-yy  hh:mm a";
    private SimpleDateFormat sdf = new SimpleDateFormat(TIME_DATE_FORMAT);

    /**
     * Creates new form SimpleDateTimeWindow
     */
    public SimpleDateTimeWindow() {
        initComponents();
        startDateTime.roll(Calendar.YEAR, -1);
        txtStartDateTime.setText(sdf.format(startDateTime.getTime()));
        txtEndDateTime.setText(sdf.format(endDateTime.getTime()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblStartDateTime = new javax.swing.JLabel();
        lblEndDateTime = new javax.swing.JLabel();
        btnCalculateDifference = new javax.swing.JButton();
        txtStartDateTime = new javax.swing.JTextField();
        txtEndDateTime = new javax.swing.JTextField();
        lblResult = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Date Time Calculator");
        setAlwaysOnTop(true);

        lblStartDateTime.setText("Start Date/Time:");

        lblEndDateTime.setText("End Date/Time:");

        btnCalculateDifference.setText("Calculate Difference");
        btnCalculateDifference.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculateDifferenceActionPerformed(evt);
            }
        });

        txtStartDateTime.setText("jTextField1");

        txtEndDateTime.setText("jTextField2");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblResult, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(btnCalculateDifference))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblStartDateTime)
                            .addComponent(lblEndDateTime))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtEndDateTime, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                            .addComponent(txtStartDateTime))))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStartDateTime)
                    .addComponent(txtStartDateTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEndDateTime)
                    .addComponent(txtEndDateTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblResult)
                .addGap(36, 36, 36)
                .addComponent(btnCalculateDifference)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalculateDifferenceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculateDifferenceActionPerformed

        CalculateDateTimeDifference calculateDateTimeDifference = new CalculateDateTimeDifference();
        String startDateValueTime = txtStartDateTime.getText();
        String endDateValueTime = txtEndDateTime.getText();

        try {
            sdf.setLenient(false);
            sdf.parse(startDateValueTime.trim());
            sdf.parse(endDateValueTime.trim());
            lblResult.setText(calculateDateTimeDifference.getCalculatedDifference(endDateValueTime, startDateValueTime, TIME_DATE_FORMAT));
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(this, "Sorry, your date must be in this format: " + TIME_DATE_FORMAT);
        }

    }//GEN-LAST:event_btnCalculateDifferenceActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalculateDifference;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblEndDateTime;
    private javax.swing.JLabel lblResult;
    private javax.swing.JLabel lblStartDateTime;
    private javax.swing.JTextField txtEndDateTime;
    private javax.swing.JTextField txtStartDateTime;
    // End of variables declaration//GEN-END:variables
}
